trigger:
- main  # Adjust this to your main branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'
  djangoSettingsModule: 'myproject.settings'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python manage.py test
  displayName: 'Run tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ef222d8c-ece0-4527-8c9a-fc715567d111'  # Your Azure Subscription ID
    appType: 'webAppLinux'
    appName: 'tegyHagzWebApp'  # Your App Service Name
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
    runtimeStack: 'PYTHON|3.9'

- script: |
    az webapp restart --name tegyHagzWebApp --resource-group tegy-hagz
  displayName: 'Restart Azure Web App'