# Generated by Django 5.1.3 on 2024-11-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='court',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
