# Generated by Django 5.1.4 on 2024-12-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_court_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='details',
            field=models.TextField(default='Details not provided'),
        ),
        migrations.AlterField(
            model_name='court',
            name='reviews',
            field=models.TextField(default='No reviews yet'),
        ),
    ]
