# Generated by Django 5.1.3 on 2024-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_court_details_alter_court_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Datacsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        # migrations.AddField(
        #     model_name='court',
        #     name='city',
        #     field=models.CharField(default=1, max_length=100),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='court',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='reviews',
            field=models.CharField(max_length=50),
        ),
        # migrations.DeleteModel(
        #     name='Schedule',
        # ),
    ]
