# Generated by Django 5.1.3 on 2024-12-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_courtschedule_datacsv_court_city_alter_court_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtschedule',
            name='court_id',
        ),
        migrations.AddField(
            model_name='courtschedule',
            name='court_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.court'),
            preserve_default=False,
        ),
    ]
