# Generated by Django 5.1.3 on 2024-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_courtschedule_court_id_court_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
