# Generated by Django 5.1.3 on 2024-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_court_city_alter_customuser_email_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_court_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
